name: Build, Package, and Release

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y dpkg-dev
    - name: Build Package
      run: |
        VERSION=$(git describe --tags --abbrev=0 2>/dev/null || echo "1.0")
        mkdir -p deb/usr/local/bin
        find . -maxdepth 1 ! -name 'deb' ! -name '.' ! -name '.git' -exec cp -r {} deb/usr/local/bin/ \;
        mkdir -p deb/DEBIAN
        cat <<EOF > deb/DEBIAN/control
        Package: wee-preference-loader
        Version: $VERSION
        Section: base
        Priority: optional
        Architecture: all
        Maintainer: Anh Duong <anhduong28@live.com>
        Description: WeePreferenceLoader tool
        EOF
        dpkg-deb --build deb "wee-preference-loader-${VERSION}.deb"
    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: wee-preference-loader
        path: "wee-preference-loader-*.deb"

    - name: Push Git Tag
      run: |
        git config user.name "anhduong28"
        git config user.email "anhduong28@live.com"
        git tag "v$VERSION"
        git push origin "v$VERSION"
